language: elixir
elixir: # Latest version of Elixir
  - 1.7
addons: # ensure that Travis-CI provisions a DB for our test:
  postgresql: '9.5'
env:
  - MIX_ENV=test
script: # run the tests:
  - mix cover
after_success:
  - bash <(curl -s https://codecov.io/bash)
